on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: sampleconregistry001.azurecr.io
        username: ${{ secrets.acr_sampleconregistry001_username }}
        password: ${{ secrets.acr_sampleconregistry001_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t sampleconregistry001.azurecr.io/myaks001:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push sampleconregistry001.azurecr.io/myaks001:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_myaks001_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaks001a741 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaks001a741`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaks001a741
        container-registry-url: sampleconregistry001.azurecr.io
        container-registry-username: ${{ secrets.acr_sampleconregistry001_username }}
        container-registry-password: ${{ secrets.acr_sampleconregistry001_password }}
        secret-name: myaks001dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaks001a741
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          sampleconregistry001.azurecr.io/myaks001:${{ github.sha }}
        imagepullsecrets: |
          myaks001dockerauth
